---
title: "Anime Data"
author: "John Collopy"
date: "9/21/2023"
output: html_document
---

```{r}
anime <- read.csv("~/Downloads/anime.csv")
View(anime)
```


```{r}
# Finding the unique Genres in the Genres column
unique_genres <- unique(anime$Genres)
unique_genres[1:5]
```

```{r}
typeof(anime$Genres)
```

```{r}
replace_genres <- function(genre_list) {
  
  genre_list <- gsub("Martial Arts", "MartialArts", genre_list)
  genre_list <- gsub("Slice of Life", "SliceofLife", genre_list)
  return(genre_list)
}

anime$Genres <- lapply(anime$Genres, function(genre_list) replace_genres(genre_list))
```

```{r}
# Putting the items in "Genres" column into a list

anime$Genres_List <- lapply(anime$Genres, function(x) unlist(strsplit(x, ", ")))
```

```{r}
#Finding the Genre that appears the most

unlisted_strings <- unlist(anime$Genres_List)
string_frequencies <- table(unlisted_strings)

# Convert the frequency table to a data frame
frequency_df <- as.data.frame(string_frequencies)

# Rename the columns
colnames(frequency_df) <- c("String", "Frequency")

# Print the frequency data frame
sorted_data <- frequency_df[order(-frequency_df$Frequency), ]

# Print the sorted data frame
print(sorted_data)
```

```{r}
# Need to get rid of Hentai, Ecchi, Harem, Yaoi, Yuri
```

```{r}
# Getting Rid of the weirdo genres
anime <- anime[!grepl("Hentai", anime$Genres),]
anime <- anime[!grepl("Ecchi", anime$Genres),]
anime <- anime[!grepl("Harem", anime$Genres),]
anime <- anime[!grepl("Yaoi", anime$Genres),]
anime <- anime[!grepl("Yuri", anime$Genres),]
```


```{r}
# Making the Year_Premiered Column

anime$Year_Premiered <- ifelse(anime$Premiered == "Unknown",
                         "Unknown",
                         sub(".* (\\d{4})", "\\1", anime$Premiered))
```

```{r}
anime$Year_Premiered
```


```{r}
breaks <- c(0,1, 10, 30, 60, Inf) 

anime$bin_episodes <- cut(as.integer(anime$Episodes), breaks = breaks)
item_counts <- table(anime$bin_episodes)
item_counts
#hist_data <- hist(anime$bin_episodes, main = "Histogram", xlab = "Bins", ylab = #"Frequency")
```

```{r}
unknown_count <- sum(anime$Episodes == "Unknown")
unknown_count
```

